name: Maven Action Test
on: [push]
jobs:
  version-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Maven  Action Test
        uses: ./
        with:
          maven-version: 3.8.2
      - name: Maven Run
        run: mvn --version
  file-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Maven
        run: |
          download_url='https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.2/apache-maven-3.8.2-bin.tar.gz'
          wget -O ${{ runner.temp }}/apache-maven-3.8.2-bin.tar.gz $download_url
      - name: Maven  Action Test
        uses: ./
        with:
          maven-file: ${{ runner.temp }}/apache-maven-3.8.2-bin.tar.gz
          maven-version: 3.8.2
      - name: Maven Run
        run: mvn --version
  url-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Maven  Action Test
        uses: ./
        with:
          url: 'https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.2/apache-maven-3.8.2-bin.tar.gz'
          maven-version: 3.8.2
      - name: Maven Run
        run: mvn --version
