name: Maven Action Test
on: [push]
jobs:
  version-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven  Action Test
        uses: ./
        with:
          maven-version: 3.8.2
      - name: Maven Run
        run: mvn --version
  file-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Maven
        run: |
          download_url='https://apache.osuosl.org/maven/maven-3/3.8.2/binaries/apache-maven-3.8.2-bin.tar.gz'
          wget -O ~/apache-maven-3.8.2-bin.tar.gz $download_url
      - name: Maven  Action Test
        uses: ./
        with:
          maven-file: ~/apache-maven-3.8.2-bin.tar.gz
          maven-version: 3.8.2
  url-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Maven  Action Test
        uses: ./
        with:
          url: 'https://apache.osuosl.org/maven/maven-3/3.8.2/binaries/apache-maven-3.8.2-bin.tar.gz'
          maven-version: 3.8.2
